version: '3'
services:
  chat-app:
    image: python:3.10.14
    volumes:
      - ./chat-app:/app
    working_dir: /app
    env_file:
      - ./chat-app/.env
    tty: true
    ports:
      - "8080:8080"
